#!/ffp/bin/sh

export PN=faad2
export PV=2.7
export PR=1
export SRC_URI="http://switch.dl.sourceforge.net/sourceforge/faac/faad2-$PV.tar.gz"
export CONFIGURE_ARGS="--prefix=$CPREFIX --disable-nls --disable-static --without-bmp --without-drm --without-mpeg4ip --without-xmms"
export COMMANDS="func_init_pkg_work_dir func_download_distfile func_unpack_distfile func_patch func_configure func_make func_make_install func_dir_ffp func_dir_install func_makepkg"
#export FFP_LDFLAGS="-L/ffp/lib -Wl,-rpath,/ffp/lib -lfrexp"
