#!/ffp/bin/sh

export PN=py27-setuptools
export PV=0.6c11
export PR=1
export SRC_URI="http://pypi.python.org/packages/source/s/setuptools/setuptools-$PV.tar.gz"
export COMMANDS="func_clean_W func_init_pkg_work_dir func_download_distfile func_unpack_distfile func_patch func_make func_make_install func_dir_ffp func_dir_install func_makepkg"
