#!/ffp/bin/sh

export PN=libevent
export PV=2.0.21
export PR=1
export SRC_URI="https://github.com/downloads/libevent/libevent/libevent-$PV-stable.tar.gz"
export CONFIGURE_ARGS="--prefix=$CPREFIX --enable-shared --disable-static"
export COMMANDS="func_init_pkg_work_dir func_download_distfile func_unpack_distfile func_patch func_configure func_make func_make_install func_dir_ffp func_dir_install func_makepkg"
