#!/ffp/bin/sh

export PN=py27-pip
export PV=1.3.1
export PR=1
export SRC_URI="https://pypi.python.org/packages/source/p/pip/pip-$PV.tar.gz"
export COMMANDS="func_clean_W func_init_pkg_work_dir func_download_distfile func_unpack_distfile func_patch func_make func_make_install func_dir_ffp func_dir_install func_makepkg"
