#!/ffp/bin/sh

export PN=lftp
export PV=4.4.8
export PR=1
export SRC_URI="http://ftp.yars.free.net/pub/source/lftp/lftp-$PV.tar.gz"
export CONFIGURE_ARGS="--prefix=$CPREFIX --with-openssl=$CPREFIX"
export COMMANDS="func_init_pkg_work_dir func_download_distfile func_unpack_distfile func_configure func_make func_make_install func_dir_ffp func_dir_install func_makepkg"