#!/ffp/bin/sh

export PN=ghostscript
export PV=9.07
export PR=1
export SRC_URI="http://downloads.ghostscript.com/public/ghostscript-$PV.tar.gz"
export COMMANDS="func_init_pkg_work_dir func_download_distfile func_unpack_distfile func_patch func_configure func_make func_make_install func_dir_ffp func_dir_install func_makepkg"
