#!/ffp/bin/sh

export PN=libjingle
export PV=0.6.14
export PR=1
export SRC_URI="http://libjingle.googlecode.com/files/libjingle-$PV.zip"
export CONFIGURE_ARGS="--prefix=$CPREFIX"
export COMMANDS="func_init_pkg_work_dir func_download_distfile func_unpack_distfile func_patch func_configure func_make func_make_install func_dir_ffp func_dir_install func_makepkg"
