#!/ffp/bin/sh

export PN=hal
export PV=0.5.14
export PR=1
export SRC_URI="http://hal.freedesktop.org/releases/hal-$PV.tar.gz"
export CONFIGURE_ARGS="--prefix=$CPREFIX --with-pci-ids=${CPREFIX}/var/lib/misc --with-usb-ids=${CPREFIX}/var/lib/misc --disable-policy-kit"
export COMMANDS="func_init_pkg_work_dir func_download_distfile func_unpack_distfile func_patch func_configure func_make func_make_install func_dir_ffp func_dir_install func_makepkg"
