#!/ffp/bin/sh

export PN=lighttpd
export PV=1.4.32
export PR=1
export SRC_URI="http://download.lighttpd.net/lighttpd/releases-1.4.x/lighttpd-$PV.tar.gz"
export CONFIGURE_ARGS="--prefix=$CPREFIX --libdir=$CPREFIX/lib/$P --program-prefix='' --with-openssl --with-pcre --with-zlib"
export COMMANDS="func_init_pkg_work_dir func_download_distfile func_unpack_distfile func_patch func_configure func_make func_make_install func_dir_ffp func_dir_install func_makepkg"
