#!/ffp/bin/sh

export PN=openldap
export PV=2.4.35
export PR=1
export SRC_URI="ftp://sunsite.cnlab-switch.ch/mirror/OpenLDAP/openldap-release/openldap-$PV.tgz"
export CONFIGURE_ARGS="--prefix=$CPREFIX"
export COMMANDS="func_init_pkg_work_dir func_download_distfile func_unpack_distfile func_patch func_configure func_make func_make_install func_dir_ffp func_dir_install func_makepkg"
