#!/ffp/bin/sh

export PN=dcled
export PV=2.0
export PR=1
export SRC_URI="http://www.last-outpost.com/~malakai/dcled/dcled-$PV.tgz"
export CONFIGURE_ARGS="--prefix=$CPREFIX"
export COMMANDS="func_init_pkg_work_dir func_download_distfile func_unpack_distfile func_patch func_make func_make_install func_dir_ffp func_dir_install func_makepkg"
