#!/ffp/bin/sh

export PN=unrar
export PV=5.0.12
export PR=1
export SRC_URI="http://rarlab.com/rar/unrarsrc-$PV.tar.gz"
export CONFIGURE_ARGS="--prefix=$CPREFIX"
export COMMANDS="func_init_pkg_work_dir func_download_distfile func_unpack_distfile func_configure func_make func_make_install func_dir_ffp func_dir_install func_makepkg"
