#!/ffp/bin/sh

export PN=libwebp
export PV=0.3.1
export PR=1
export SRC_URI="https://webp.googlecode.com/files/libwebp-$PV.tar.gz"
export CONFIGURE_ARGS="--prefix=$CPREFIX --with-pnglibdir=/ffp/lib --with-tifflibdir=/ffp/lib  --with-giflibdir=/ffp/lib --with-sysroot=/ffp/lib"
export COMMANDS="func_init_pkg_work_dir func_download_distfile func_unpack_distfile func_patch func_configure func_make func_make_install func_dir_ffp func_dir_install func_makepkg"
