#!/ffp/bin/sh

export PN=libzen
export PV=0.4.29
export PR=1
export SRC_URI="http://switch.dl.sourceforge.net/project/zenlib/ZenLib%20-%20Sources/$PV/libzen_$PV.tar.gz"
export CONFIGURE_ARGS="--prefix=$CPREFIX"
export COMMANDS="func_init_pkg_work_dir func_download_distfile func_unpack_distfile func_patch func_configure func_make func_make_install func_dir_ffp func_dir_install func_makepkg"
