#!/ffp/bin/sh

export PN=libassuan
export PV=2.1.0
export PR=1
export SRC_URI="ftp://ftp.gnupg.org/gcrypt/$PN/$PN-$PV.tar.bz2"
export CONFIGURE_ARGS="--prefix=$CPREFIX"
export COMMANDS="func_init_pkg_work_dir func_download_distfile func_unpack_distfile func_patch func_configure func_make func_make_install func_dir_ffp func_dir_install func_makepkg"
