#!/ffp/bin/sh

export PN=python
export PV=2.7.3
export PR=1
export SRC_URI="http://www.python.org/ftp/python/$PV/Python-$PV.tgz"
export CONFIGURE_ARGS="--prefix=$CPREFIX --with-threads --enable-ipv6 --enable-shared --docdir=/ffp/share/doc/$PN-$PV --mandir=/ffp/share/man --infodir=/ffp/share/doc"
export COMMANDS="func_init_pkg_work_dir func_download_distfile func_unpack_distfile func_patch func_configure func_make func_make_install func_dir_ffp func_dir_install func_makepkg"
