#!/ffp/bin/sh

export PN=libpng
export PV=1.6.2
export PR=1
export SRC_URI="http://switch.dl.sourceforge.net/project/libpng/libpng15/$PV/libpng-$PV.tar.xz"
export CONFIGURE_ARGS="--prefix=$CPREFIX"
export COMMANDS="func_init_pkg_work_dir func_download_distfile func_unpack_distfile func_patch func_configure func_make func_make_install func_dir_ffp func_dir_install func_makepkg"
