#!/ffp/bin/sh

export PN=aspell6-it
export PV=2.2_20050523-0
export PR=1
export SRC_URI="ftp://ftp.gnu.org/gnu/aspell/dict/it/aspell6-it-2.2_20050523-0.tar.bz2"
export CONFIGURE_ARGS="--vars DESTDIR=$D"
export COMMANDS="func_init_pkg_work_dir func_download_distfile func_unpack_distfile func_patch func_configure func_make func_make_install func_dir_ffp func_dir_install func_makepkg"
