#!/ffp/bin/sh

export PN=mkvtoolnix
export PV=6.2.0
export PR=1
export SRC_URI="https://www.bunkus.org/videotools/mkvtoolnix/sources/mkvtoolnix-$PV.tar.bz2"
export CONFIGURE_ARGS="--prefix=$CPREFIX"
export COMMANDS="func_init_pkg_work_dir func_download_distfile func_unpack_distfile func_patch func_configure func_make func_make_install func_dir_ffp func_dir_install func_makepkg"
export COMMAND_MAKE"drake"
