#!/ffp/bin/sh

export PN=rsync
export PV=3.1.0
export PR=1
export SRC_URI="https://rsync.samba.org/ftp/rsync/src/rsync-$PV.tar.gz"
export CONFIGURE_ARGS="--prefix=$CPREFIX --disable-nls --disable-debug --disable-locale --with-rsyncd-conf=/ffp/etc/rsyncd.conf"
export COMMANDS="func_init_pkg_work_dir func_download_distfile func_unpack_distfile func_patch func_configure func_make func_make_install func_dir_ffp func_dir_install func_makepkg"
