#!/ffp/bin/sh

export PN=libmcrypt
export PV=2.6.7
export PR=1
export SRC_URI="http://switch.dl.sourceforge.net/project/mcrypt/Libmcrypt/$PV/libmcrypt-$PV.tar.gz"
export CONFIGURE_ARGS="--prefix=$CPREFIX --disable-posix-threads"
export COMMANDS="func_init_pkg_work_dir func_download_distfile func_unpack_distfile func_patch func_configure func_make func_make_install func_dir_ffp func_dir_install func_makepkg"
