#!/ffp/bin/sh

export PN=module-init-tools
export PV=3.15
export PR=1
export SRC_URI="https://www.kernel.org/pub/linux/utils/kernel/module-init-tools/module-init-tools-$PV.tar.xz"
export CONFIGURE_ARGS="--prefix=$CPREFIX --with-moddir=/ffp/lib/modules"
export COMMANDS="func_init_pkg_work_dir func_download_distfile func_unpack_distfile func_patch func_configure func_make func_make_install func_dir_ffp func_dir_install func_makepkg"
