#!/ffp/bin/sh

export PN=py27-virtualenv
export PV=1.9.1
export PR=1
export SRC_URI="https://pypi.python.org/packages/source/v/virtualenv/virtualenv-1.9.1.tar.gz"
export COMMANDS="func_clean_W func_init_pkg_work_dir func_download_distfile func_unpack_distfile func_patch func_make func_make_install func_dir_ffp func_dir_install func_makepkg"
