#!/ffp/bin/sh

export PN=cksfv
export PV=1.3.14
export PR=1
export SRC_URI="http://zakalwe.fi/~shd/foss/cksfv/files/cksfv-$PV.tar.gz"
export COMMANDS="func_init_pkg_work_dir func_download_distfile func_unpack_distfile func_configure func_make func_make_install func_dir_ffp func_dir_install func_makepkg"
