#!/ffp/bin/sh

export PN=usbids
export PV=20120627
export PR=1
export SRC_URI="http://www.linux-usb.org/usb.ids"
export CONFIGURE_ARGS="--prefix=$CPREFIX"
export COMMANDS="func_init_pkg_work_dir func_download_distfile func_unpack_distfile func_make_install func_dir_install func_makepkg"
