#!/ffp/bin/sh

export PN=libmad
export PV=0.15.1b
export PR=1
export SRC_URI="ftp://ftp.mars.org/pub/mpeg/libmad-$PV.tar.gz"
export CONFIGURE_ARGS="--prefix=$CPREFIX"
export COMMANDS="func_init_pkg_work_dir func_download_distfile func_unpack_distfile func_patch func_configure func_make func_make_install func_dir_ffp func_dir_install func_makepkg"
