#!/ffp/bin/sh

export PN=ffmpeg
export PV=0.10.2
export PR=1
export SRC_URI="http://ffmpeg.org/releases/ffmpeg-$PV.tar.gz"
export CONFIGURE_ARGS="--prefix=$CPREFIX --disable-static --enable-shared --enable-gpl --enable-nonfree --enable-small --disable-encoder=aac --disable-decoder=aac --disable-armv6 --disable-armv6t2 --disable-armvfp"
export COMMANDS="func_init_pkg_work_dir func_download_distfile func_unpack_distfile func_patch func_configure func_make func_make_install func_dir_ffp func_dir_install func_makepkg"
