#!/ffp/bin/sh

export PN=avahi
export PV=0.6.31
export PR=1
export SRC_URI="http://avahi.org/download/avahi-$PV.tar.gz"
export CONFIGURE_ARGS="--prefix=$CPREFIX --enable-libdaemon --with-distro=none --enable-dbus --disable-gtk --disable-gtk3 --disable-mono --disable-python --disable-qt3 --disable-qt4 --disable-stack-protector"
export COMMANDS="func_init_pkg_work_dir func_download_distfile func_unpack_distfile func_patch func_configure func_make func_make_install func_dir_ffp func_dir_install func_makepkg"
