echo "###############################################################################"
echo "#      _______ _______ _______ _______ __   _ _______ _____  _____  __   _    #"
echo "#      |_____|    |       |    |______ | \  |    |      |   |     | | \  |    #"
echo "#      |     |    |       |    |______ |  \_|    |    __|__ |_____| |  \_|    #"
echo "#                                                                             #"
echo "###############################################################################"
echo "#                          _  _ _   _ ____ ____ _                             #"
echo "#                          |\/|  \_/  [__  |  | |                             #"
echo "#                          |  |   |   ___] |_\| |___                          #"
echo "#                                                                             #"
echo "###############################################################################"
echo "#                                                                             #"
echo "# This package is only compatible with the corresponding tutorial of Uli:     #"
echo "#  - http://wolf-u.li/nas/                                                    #"
echo "#  - http://nas-tweaks.net/                                                   #"
echo "#                                                                             #"
echo "# Please ensure to use the newest start-script in /ffp/start/ and rename if   #"
echo "# necessary.                                                                  #"
echo "#                                                                             #"
echo "# Also it is not compatible with former file structures of Version <5.5,      #"
echo "# so please ensure to adjust your my.cnf to your existing file system         #"
echo "# structure if you upgrade from these versions.                               #"
echo "#                                                                             #"
echo "# Have fun with MySQL :)                                                      #"
echo "#                                                                             #"
echo "###############################################################################"