echo "|------------------------------------------------|"
echo "| Please ensure that aspell is installed!        |"
echo "| If you want to have syntax highlighting, you   |"
echo "| just need to enable it:                        |"
echo "|   mv /ffp/etc/examples/nanorc /ffp/etc/        |"
echo "|                                                |"
echo "| If you need more assistance, follow the        |"
echo "| instructions at:                               |"
echo "|   http://nas-tweaks.net/79/                    |"
echo "|------------------------------------------------|"
