#!/ffp/bin/sh

export PN=nano
export PV=2.2.6
export PR=1
export SRC_URI="http://www.nano-editor.org/dist/v2.2/nano-$PV.tar.gz"
export CONFIGURE_ARGS="--prefix=$CPREFIX --enable-all --disable-wrapping-as-root"
export COMMANDS="func_init_pkg_work_dir func_download_distfile func_unpack_distfile func_patch func_configure func_make func_make_install func_dir_ffp func_dir_install func_makepkg"
