#!/ffp/bin/sh

export PN=libvorbis
export PV=1.3.3
export PR=1
export SRC_URI="http://downloads.xiph.org/releases/vorbis/libvorbis-$PV.tar.gz"
export CONFIGURE_ARGS="--prefix=$CPREFIX"
export COMMANDS="func_init_pkg_work_dir func_download_distfile func_unpack_distfile func_patch func_configure func_make func_make_install func_dir_ffp func_dir_install func_makepkg"
