#!/ffp/bin/sh

export PN=libhid
export PV=0.2.16
export PR=1
export SRC_URI="http://alioth.debian.org/frs/download.php/1958/libhid-$PV.tar.gz"
export CONFIGURE_ARGS="--prefix=$CPREFIX --disable-swig PKG_CONFIG=/ffp/lib/pkgconfig/"
export COMMANDS="func_init_pkg_work_dir func_download_distfile func_unpack_distfile func_patch func_configure func_make func_make_install func_dir_ffp func_dir_install func_makepkg"
