#!/ffp/bin/sh -xe

export PN=gnutls
export PV=3.2.1
export PR=1
export SRC_URI="ftp://ftp.gnutls.org/gcrypt/gnutls/v3.2/gnutls-$PV.tar.xz"
export CONFIGURE_ARGS="--prefix=$CPREFIX"
export COMMANDS="func_init_pkg_work_dir func_download_distfile func_unpack_distfile func_configure func_make func_make_install func_dir_ffp func_dir_install func_makepkg"

export FFP_LDFLAGS="-L/ffp/lib -Wl,-rpath,/ffp/lib -lpthread"
# -L/ffp/lib/libpthread.so.0"
export LIB+=-lpthread
