#!/ffp/bin/sh

export PN=git
export PV=1.8.3.1
export PR=1
export SRC_URI="http://git-core.googlecode.com/files/git-$PV.tar.gz"
export CONFIGURE_ARGS="--prefix=/ffp --build=$GNU_BUILD --host=$GNU_HOST --mandir=$MANDIR --infodir=$INFODIR --disable-nls --with-openssl --with-curl --with-expat --with-iconv=/ffp  --with-gitconfig=/ffp/etc/gitconfig --with-gitattributes=/ffp/etc/gitattributes --with-pager=/ffp/bin/less --with-editor=/ffp/bin/vim --with-shell=/ffp/bin/sh --with-perl=/ffp/bin/perl --without-python --with-zlib=/ffp --without-tcltk"
export COMMANDS="func_init_pkg_work_dir func_download_distfile func_unpack_distfile func_patch func_configure func_make func_make_install func_dir_ffp func_dir_install func_makepkg"
