#!/ffp/bin/sh

export PN=nut
export PV=2.6.5
export PR=1
export SRC_URI="http://www.networkupstools.org/source/2.6/nut-$PV.tar.gz"
export CONFIGURE_ARGS="--prefix=$CPREFIX --with-pci-ids=${CPREFIX}/var/lib/misc --with-usb-ids=${CPREFIX}/var/lib/misc"
export COMMANDS="func_init_pkg_work_dir func_download_distfile func_unpack_distfile func_patch func_configure func_make func_make_install func_dir_ffp func_dir_install func_makepkg"
